name: 'PR title check'
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: dylanvann/check-pull-request-title@v0.1.14å
        with:
          # Match pull request titles in the form UI-1234 - Message.
          pattern: '^UI-\d* - '
